In [1]:
import numpy as np
import matplotlib.pyplot as plt

import math as ma

In [2]:
def void_mesh(d1,d2,p,m,R,element_type):
    q = np.array([[0,0],[d1,0],[0,d2],[d1,d2]])
    PD = 2
    NoN = (m+1)*(p+1)*2+(m+1)*(p-1)*2
    NoE = 4*p*m
    NPE = 4
    NL = np.zeros([NoN,PD])
    a = (q[1,0]-q[0,0])/p
    b = (q[2,1]-q[0,1])/p
    
    coor11 = np.zeros([(p+1)*(m+1),PD])
    
    for i in range(1,p+2):
        coor11[i-1,0] = q[0,0]+(i-1)*a
        coor11[i-1,1] = q[0,1]
    for i in range(1,p+2):
        coor11[m*(p+1)+i-1,0] = d1/2 + R*np.cos((5*ma.pi/4)+(i-1)*ma.pi/(2*p))
        coor11[m*(p+1)+i-1,1] = d2/2 + R*np.sin((5*ma.pi/4)+(i-1)*ma.pi/(2*p))
    for i in range(1,m):
        for j in range(1,p+2):
            dx = (coor11[m*(p+1)+j-1,0]-coor11[j-1,0])/m
            dy = (coor11[m*(p+1)+j-1,1]-coor11[j-1,1])/m
            coor11[i*(p+1)+j-1,0] = coor11[(i-1)*(p+1)+j-1,0] + dx
            coor11[i*(p+1)+j-1,1] = coor11[(i-1)*(p+1)+j-1,1] + dy
    
    coor22 =np.zeros([(p+1)*(m+1),PD])
    for i in range(1,p+2):
        coor22[i-1,0] = q[2,0]+(i-1)*a
        coor22[i-1,1] = q[2,1]
    for i in range(1,p+2):
        coor22[m*(p+1)+i-1,0] = d1/2 + R*np.cos((3*ma.pi/4)-(i-1)*ma.pi/(p*2))
        coor22[m*(p+1)+i-1,1] = d2/2 + R*np.sin((3*ma.pi/4)-(i-1)*ma.pi/(2*p))
    for i in range(1,m):
        for j in range(1,p+2):
            dx = (coor22[m*(p+1)+j-1,0]-coor22[j-1,0])/m
            dy = (coor22[m*(p+1)+j-1,1]-coor22[j-1,1])/m
            coor22[i*(p+1)+j-1,0] = coor22[(i-1)*(p+1)+j-1,0] + dx
            coor22[i*(p+1)+j-1,1] = coor22[(i-1)*(p+1)+j-1,1] + dy
            
    coor33 = np.zeros([(p-1)*(m+1),PD])
    for i in range(1,p):
        coor33[i-1,0] = q[0,0]
        coor33[i-1,1] = q[0,1] + i*b
    for i in range(1,p):
        coor33[m*(p-1)+i-1,0] = d1/2 + R*np.cos((5*ma.pi/4)-(i)*ma.pi/(p*2))
        coor33[m*(p-1)+i-1,1] = d2/2 + R*np.sin((5*ma.pi/4)-(i)*ma.pi/(p*2))
    for i in range(1,m):
        for j in range(1,p):
            dx = (coor33[m*(p-1)+j-1,0]-coor33[j-1,0])/m
            dy = (coor33[m*(p-1)+j-1,1]-coor33[j-1,1])/m
            coor33[i*(p-1)+j-1,0] = coor33[(i-1)*(p-1)+j-1,0] + dx
            coor33[i*(p-1)+j-1,1] = coor33[(i-1)*(p-1)+j-1,1] + dy
     
    coor44 = np.zeros([(p-1)*(m+1),PD])
    for i in range(1,p):
        coor44[i-1,0] = q[1,0]
        coor44[i-1,1] = q[1,1] + i*b
    for i in range(1,p):
        coor44[m*(p-1)+i-1,0] = d1/2 + R*np.cos((7*ma.pi/4)+(i)*ma.pi/(p*2))
        coor44[m*(p-1)+i-1,1] = d2/2 + R*np.sin((7*ma.pi/4)+(i)*ma.pi/(p*2))
    for i in range(1,m):
        for j in range(1,p):
            dx = (coor44[m*(p-1)+j-1,0]-coor44[j-1,0])/m
            dy = (coor44[m*(p-1)+j-1,1]-coor44[j-1,1])/m
            coor44[i*(p-1)+j-1,0] = coor44[(i-1)*(p-1)+j-1,0] + dx
            coor44[i*(p-1)+j-1,1] = coor44[(i-1)*(p-1)+j-1,1] + dy
     
    for i in range(1,m+2):
        NL[(i-1)*4*p:i*4*p,:] = np.vstack([coor11[(i-1)*(p+1):i*(p+1),:],coor44[(i-1)*(p-1):i*(p-1),:],np.flipud(coor22[(i-1)*(p+1):i*(p+1),:]),np.flipud(coor33[(i-1)*(p-1):i*(p-1),:])])
    

    EL = np.zeros([NoE,NPE])
    for i in range(1,m+1):
        for j in range(1,4*p+1):
            if j == 1:
                EL[(i-1)*4*p+j-1,0] = (i-1)*4*p + j
                EL[(i-1)*4*p+j-1,1] = EL[(i-1)*4*p+j-1,0] + 1
                EL[(i-1)*4*p+j-1,3] = EL[(i-1)*4*p+j-1,0] + 4*p
                EL[(i-1)*4*p+j-1,2] = EL[(i-1)*4*p+j-1,3] + 1
            elif j == 4*p:
                EL[(i-1)*4*p+j-1,0] = i*4*p
                EL[(i-1)*4*p+j-1,1] = (i-1)*4*p + 1
                EL[(i-1)*4*p+j-1,2] = EL[(i-1)*4*p+j-1,0] + 1
                EL[(i-1)*4*p+j-1,3] = EL[(i-1)*4*p+j-1,0] + 4*p 
            else:
                EL[(i-1)*4*p+j-1,0] = EL[(i-1)*4*p+j-2,1]
                EL[(i-1)*4*p+j-1,3] = EL[(i-1)*4*p+j-2,2]
                EL[(i-1)*4*p+j-1,2] = EL[(i-1)*4*p+j-1,3] + 1
                EL[(i-1)*4*p+j-1,1] = EL[(i-1)*4*p+j-1,0] + 1
    if element_type == 'D2TR3N':
        NPEn = 3
        NoEn = 2*NoE
        ELn = np.zeros([NoEn,NPE])
        for i in range(1,NoE+1):
            ELn[2*(i-1),0] = EL[i-1,0]
            ELn[2*(i-1),1] = EL[i-1,1]
            ELn[2*(i-1),2] = EL[i-1,2]
            ELn[2*(i-1)+1,0] = EL[i-1,0]
            ELn[2*(i-1)+1,1] = EL[i-1,2]
            ELn[2*(i-1)+1,2] = EL[i-1,3]
        EL = ELn
    EL = EL.astype(int)
    return NL,EL


In [3]:
d1 = 1
d2 = 1
p = 3
m = 8
R = 0.05
element_type = "D2QU4N"
NL, EL = void_mesh(d1,d2,p,m,R,element_type)
NoN = np.size(NL,0)
NoE = np.size(EL,0)
plt.figure(1)

count = 1
#for i in range(0,NoN):
 #   plt.annotate(count,xy = (NL[i,0],NL[i,1]))
  #  count +=1
if element_type == 'D2QU4N':
   # count2 = 1
    #for j in range(0,NoE):
     #   plt.annotate(count2,xy=((NL[EL[j,0]-1,0]+NL[EL[j,1]-1,0]+NL[EL[j,2]-1,0]+NL[EL[j,3]-1,0])/4,(NL[EL[j,0]-1,1]+NL[EL[j,1]-1,1]+NL[EL[j,2]-1,1]+NL[EL[j,3]-1,1])/4),c = 'blue')
      #  count2 += 1
    x0, y0 = NL[EL[:,0]-1,0], NL[EL[:,0]-1,1]
    x1, y1 = NL[EL[:,1]-1,0], NL[EL[:,1]-1,1]
    x2, y2 = NL[EL[:,2]-1,0], NL[EL[:,2]-1,1]
    x3, y3 = NL[EL[:,3]-1,0], NL[EL[:,3]-1,1]
    plt.plot(np.array([x0,x1]),np.array([y0,y1]),'red',linewidth=1)
    plt.plot(np.array([x1,x2]),np.array([y1,y2]),'red',linewidth=1)
    plt.plot(np.array([x2,x3]),np.array([y2,y3]),'red',linewidth=1)
    plt.plot(np.array([x3,x0]),np.array([y3,y0]),'red',linewidth=1)


IndexError: index 32 is out of bounds for axis 0 with size 20

In [1]:
element_type = 'D2TR3N'
NL, EL = void_mesh(d1,d2,p,m,R,element_type)
if element_type == 'D2TR3N':
    #count2 = 1
    #for j in range(0,NoE):
     #   plt.annotate(count2,xy = ((NL[EL[j,0]-1,0]+NL[EL[j,1]-1,0]+NL[EL[j,2]-1,0])/3,(NL[EL[j,0]-1,1]+NL[int(EL[j,1])-1,1]+NL[int(EL[j,2])-1,1])/4),c = 'blue')
      #  count2 += 1
    x0, y0 = NL[EL[:,0]-1,0], NL[EL[:,0]-1,1]
    x1, y1 = NL[EL[:,1]-1,0], NL[EL[:,1]-1,1]
    x2, y2 = NL[EL[:,2]-1,0], NL[EL[:,2]-1,1]
    plt.plot(np.array([x0,x1]),np.array([y0,y1]),'red',linewidth=1);
    plt.plot(np.array([x1,x2]),np.array([y1,y2]),'red',linewidth=1);
    plt.plot(np.array([x2,x0]),np.array([y2,y0]),'red',linewidth=1);
    

NameError: name 'void_mesh' is not defined

In [91]:
EL

array([[  1,   2,  22,   0],
       [  1,  22,  21,   0],
       [  2,   3,  23,   0],
       [  2,  23,  22,   0],
       [  3,   4,  24,   0],
       [  3,  24,  23,   0],
       [  4,   5,  25,   0],
       [  4,  25,  24,   0],
       [  5,   6,  26,   0],
       [  5,  26,  25,   0],
       [  6,   7,  27,   0],
       [  6,  27,  26,   0],
       [  7,   8,  28,   0],
       [  7,  28,  27,   0],
       [  8,   9,  29,   0],
       [  8,  29,  28,   0],
       [  9,  10,  30,   0],
       [  9,  30,  29,   0],
       [ 10,  11,  31,   0],
       [ 10,  31,  30,   0],
       [ 11,  12,  32,   0],
       [ 11,  32,  31,   0],
       [ 12,  13,  33,   0],
       [ 12,  33,  32,   0],
       [ 13,  14,  34,   0],
       [ 13,  34,  33,   0],
       [ 14,  15,  35,   0],
       [ 14,  35,  34,   0],
       [ 15,  16,  36,   0],
       [ 15,  36,  35,   0],
       [ 16,  17,  37,   0],
       [ 16,  37,  36,   0],
       [ 17,  18,  38,   0],
       [ 17,  38,  37,   0],
       [ 18,  

In [79]:
import numpy as np
import matplotlib.pyplot as plt

import math as ma

In [80]:
K = np.array([[4,0,0,-1],[-2,1, 1, 0],[3,0,-1,0],[0,-2,0,1]])
b = np.zeros((1,4))
a = np.array([0,2,0,0])
rig1 = K.dot(a)


In [81]:
rig1

array([ 0,  2,  0, -4])

In [82]:
an = -np.linalg.solve(K,rig1)

In [85]:
an

array([-0., -2.,  0., -0.])

In [86]:
an+rig1

array([ 0.,  0.,  0., -4.])

In [60]:
for i in range(3):
    if abs(rig1[i])>10e-6:
        K[i,:] = K[i,:]*0
        K[:,i] = K[:,i]*0
        K[i,i] = 1

In [61]:
K

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [62]:
an = -np.linalg.solve(K,rig1)

In [63]:
an

array([-1.,  4.,  4.,  3.])

In [64]:
for i in range(len(a.T)):
    if abs(a[i])>0:
        an[i] = a[i] 

In [65]:
an

array([-1.,  2.,  4.,  3.])

In [79]:
np.shape(a)

(1, 4)